### PR TITLE
🚀 Deploy storefront

### PR DESCRIPTION
**Pull request by vnys**
118 images updated 🤔 
Does this sound correct @equinor/eds-ux?

### CODE REVIEW

**Comment by mimarz** [comment]
@vnys have you looked at the images? Curious how this looks now with changes done in #962

**Comment by lucasveil** [comment]
I haven't uploaded nor updated any image on my last documentation update for variants. I have updated the figma links though, does that count as an image in the storefront?

**Comment by vnys** [comment]
> have you looked at the images?

Haven’t checked all the images, but I’ve browsed quickly through a few pages at https://eds-storefront-development.azurewebsites.net

**Comment by vnys** [comment]
> I haven't uploaded nor updated any image on my last documentation update for variants. I have updated the figma links though, does that count as an image in the storefront?

If you make changes in tokens or components in Figma then that results in an updated image when we run the Figma Broker, so maybe the re-organisation is the reason there are so many updated images…

**Comment by mimarz** [comment]
> > I haven't uploaded nor updated any image on my last documentation update for variants. I have updated the figma links though, does that count as an image in the storefront?
> 
> If you make changes in tokens or components in Figma then that results in an updated image when we run the Figma Broker, so maybe the re-organisation is the reason there are so many updated images…

true true, its just based of the unique id that figma has for its images, these changes for each version figma has of a file if something within that image is changed. So either the re-organization or variants...

**Comment by mimarz** [comment]
@vnys A lot of the pages are missing images. Buttons, lists and toc to name a few... Maybe this calls for an issue to investigate...

**Comment by mimarz** [comment]
> I haven't uploaded nor updated any image on my last documentation update for variants. I have updated the figma links though, does that count as an image in the storefront?

@lucasveil These are the images exported when using <FigmaImage /> :) 
```
<FigmaImage
  url="https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/Desktop-UI?node-id=1%3A4"
  alt="Figma design of primary buttons"
/>
```

**Comment by vnys** [comment]
> @vnys A lot of the pages are missing images. Buttons, lists and toc to name a few... Maybe this calls for an issue to investigate...

Sounds like it does, regression tests would have been nice – too many risks for human error the way things are now. I’ll look into it next year – don’t have the time this week 😉

**Comment by mimarz** [comment]
> > @vnys A lot of the pages are missing images. Buttons, lists and toc to name a few... Maybe this calls for an issue to investigate...
> 
> Sounds like it does, regression tests would have been nice – too many risks for human error the way things are now. I’ll look into it next year – don’t have the time this week 😉

I compared the urls for these, and its because of the re-organization(#962) that they are missing, because they got new urls now

**Review by mimarz — CHANGES_REQUESTED** [review]
As we agreed to drop the updating of images, we should revert changes done in [update images commit](https://github.com/equinor/design-system/pull/977/commits/0a55a663e27c93205e89e9568cc584cb303b7630)

**Comment by vnys** [comment]
> drop the updating of images

That commit has now been delegated to the history disposal unit and only exists in a parallel universe

**Review by mimarz — APPROVED** [review]
LGTM 👍

**Pull request merged**
