### PR TITLE
Updated status for components on Storefront

### LINKED ISSUE #547: Update component status

### PR DESCRIPTION
**Pull request by mimarz**
resolves #547

### CODE REVIEW

**Review by pomfrida — CHANGES_REQUESTED** [review]
Snackbar and Progress Indicators need to be changed too

**Comment by pomfrida** [comment]
+ The [Link](https://eds-storefront-docz.azurewebsites.net/components/links/) component is confused by the [Button Link](https://eds-storybook-react.azurewebsites.net/?path=/story/components-button--link), we don't have a React `Link` component yet... But it should be easy to create so I can do it first thing tomorrow. I also need to update [Breadcrumbs](https://eds-storybook-react.azurewebsites.net/?path=/story/components-breadcrumbs--variations) after `Link` is complete.

**Comment by mimarz** [comment]
> & The [Link](https://eds-storefront-docz.azurewebsites.net/components/links/) component is confused by the [Button Link](https://eds-storybook-react.azurewebsites.net/?path=/story/components-button--link), we don't have a React `Link` component yet... But it should be easy to create so I can do it first thing tomorrow. TTYL I'm going to play some BOTW now 😆

No, but we have `<Typography link>Link me!</Typography>` which is basically the [Link](https://eds-storefront-docz.azurewebsites.net/components/links/) I think we agreed on some meeting that the Typography component would replace the Link component for now..

**Review by pomfrida — APPROVED** [review]
👍

**Review by vnys — APPROVED** [review]
LGTM 👍

**Pull request merged**
