### PR TITLE
🚚  Categorise stories

### LINKED ISSUE #1800: Use same category headers in Storybook as in Figma
A year ago Bendik [categorised all the components](https://github.com/equinor/design-system/issues/962) in Figma to make them easier to find. The plan was to do the same in the Storybook, but we never got around to doing that. I suggest we do that during the holidays when we (hopefully) don’t have any pull requests or feature branches that haven’t been merged into develop.

### PR DESCRIPTION
**Pull request by vnys**
Use the same category headers in Storybook as we do in Figma and Zeroheight.

Resolves #1800

### CODE REVIEW

**Comment by vnys** [comment]
**Notes**

- Tabs are missing in Zeroheight
- Checkbox and radiobuttons are grouped as “Selection Controls” in Zeroheight

**Comment by vnys** [comment]
**Components that only exist in code**

- Input
- Avatar
- Group (missing tests and stories)
- EdsProvider (missing tests and stories)
- Icon
- Label
- Paper (missing tests and stories)
- TextArea (missing tests and stories)
- Typography

**Comment by vnys** [comment]
- Token story is missing

**Comment by mimarz** [comment]
> * Token story is missing

#1586

**Comment by mimarz** [comment]
I think we need to have a discussion on this and figure out how its wired up to Zeroheight. I see the benefit of having a red line with categories in Zeroheight and Figma, but I felt it was harder to find components now and see which package you can find them in… 🤔

**Comment by vnys** [comment]
I think the keyword here is consistency. If you look at a component in the Storybook, you should know how to find that in Figma and Zeroheight – and vice versa. Having the same mental map of where the components belong whether you’re in Figma or Storybook will make it easier to navigate between them, and I don’t think that’s going to be an issue once you get used to it.

If there’s a particular component that’s difficult to find, however, it could be that it should have been in a different category, and if so we have to solve that in Figma an Zeroheight as well.

I see your point about which package the components belong to, so that should be addressed – I’ll create an issue for that.

**Comment by mimarz** [comment]
> I think the keyword here is consistency. If you look at a component in the Storybook, you should know how to find that in Figma and Zeroheight – and vice versa. Having the same mental map of where the components belong whether you’re in Figma or Storybook will make it easier to navigate between them, and I don’t think that’s going to be an issue once you get used to it.
> 
> If there’s a particular component that’s difficult to find, however, it could be that it should have been in a different category, and if so we have to solve that in Figma an Zeroheight as well.
> 
> I see your point about which package the components belong to, so that should be addressed – I’ll create an issue for that.

I think we should do a spike on how to write our component stories, which headings to have etc. Installation, usage, accessibility and compact are a few headings that comes to mind which maybe every component story should have 🤔

**Comment by vnys** [comment]
> Installation, usage, accessibility and compact are a few stories that comes to mind which every component story should have 🤔

I agree, we should have a common template.

**Comment by mimarz** [comment]
> > Installation, usage, accessibility and compact are a few stories that comes to mind which every component story should have 🤔
> 
> I agree, we should have a common template.

Made issue #1850 for followup on this.

**Review by mimarz — APPROVED** [review]
Its a good start. Brings into light the work we have left on developer documentation 🙈

#1850 #1849

**Pull request merged**
