### PR TITLE
Refactor Sidesheet to typescript

### LINKED ISSUE #559: Refactor Side sheet to Typescript
Create typings for [Side sheet](https://eds.equinor.com/components/side-sheet/)

Make sure you fork the repository and branch from `typescript` before starting on this issue

### PR DESCRIPTION
**Pull request by joelmheim**
Resolves #559.

All tests are running except Chips which is fixed by previous PR #705. Storybook is also working as it should.

### CODE REVIEW

**Comment by mimarz** [comment]
@joelmheim Please update your branch with the latest changes from `typescript` so we can get this PR reviewed :)

**Comment by joelmheim** [comment]
There you go!

**Review by mimarz — APPROVED** [review]
LGTM 👍

**Review by wenche — APPROVED** [review]
LGTM 👍 

Thanks for contributing (again! 😄  )

**Pull request merged**
