### PR TITLE
⬆️ Upgraded downshift to 7.0.1

### LINKED ISSUE #2633: Update Downshift to 7.0.x
Currently we are on 6.1.12
Version 7 brings about breaking changes. [Migration guide](https://github.com/downshift-js/downshift/blob/master/src/hooks/MIGRATION_V7.md)

Unfortunately it seems they have not fixed the react 18 issue yet

### PR DESCRIPTION
**Pull request by denektenina**
resolves #2633

### CODE REVIEW

**Comment by oddvernes** [comment]
Need to update snapshots for the components changed 📸

**Comment by mimarz** [comment]
Might I suggest its maybe time to remove `MultiSelect` and `SingleSelect`? 🙂

**Comment by oddvernes** [comment]
> Might I suggest its maybe time to remove `MultiSelect` and `SingleSelect` (in a separate issue ofc)? 🙂

We literally discussed this yesterday, and that is indeed the plan (in a seperate issue) 😀

**Comment by oddvernes** [comment]
Downshift should be updated in eds-labs-react too since it is used by TimePicker

**Review by oddvernes — APPROVED** [review]
LGTM! release is done so now this can be merged

**Pull request merged**
