### PR TITLE
✨ Combobox data-model support with data property

### LINKED ISSUE #1416: Support different data-models in Single-/MultiSelect components
In 11/10 cases our selectionlists are based on name+id models `{ "name": "Select me", "id": "long-ass-guid" }`, but EDS only has support for simple strings. 

**Describe the solution you'd like**
Being able to send in a different datatype, or to send in an Option render-prop where we can connect the id to the name ourselves.

### PR DESCRIPTION
**Pull request by mimarz**
resolves #1416

### CODE REVIEW

**Comment by oddvernes** [comment]
Everything seems to be in working order. One thing though perhaps is screen reader is abit janky (windows narrator on microsoft edge) it reads every line twice and says 'selected' which is because the line is focused but not actually selected as in checked, toggling state between selected (checked) and not selected (unchecked) in a multiple the reader remains mute

**Comment by oddvernes** [comment]
Testing voiceover on mac, and it is considerably better here. It reads each line only once, it reads when you deselect an option in multiple but not when you select an option

**Comment by mimarz** [comment]
> Everything seems to be in working order. One thing though perhaps is screen reader is abit janky (windows narrator on microsoft edge) it reads every line twice and says 'selected' which is because the line is focused but not actually selected as in checked, toggling state between selected (checked) and not selected (unchecked) in a multiple the reader remains mute

Hmm, I only get it read once on MacOs (Voiceover). This has however been a challenge with downshift and comboboxes in general. The same faults can be found on `Single` & `Multi` selects today.

**Review by oddvernes — APPROVED** [review]
I think this is good enough, considering the limitations with downshift

**Pull request merged**
