### PR TITLE
Bugfix/add missing bounds check for findIndex

### PR DESCRIPTION
**Pull request by mhwaage**
* Adds a bounds check for Autocomplete's findIndex, to prevent infinite recursion once the index has gone beyond bounds.
* Adds test to prevent regression

### CODE REVIEW

**Comment by oddvernes** [comment]
I thought this had been fixed by https://github.com/equinor/design-system/pull/3534 but I guess I missed something? I'll take a look when i return from vacation next week!

**Comment by mhwaage** [comment]
> I thought this had been fixed by #3534 but I guess I missed something? I'll take a look when i return from vacation next week!

Possible that I implemented this fix on an outdated version, I will verify!

**Comment by mhwaage** [comment]
> > I thought this had been fixed by #3534 but I guess I missed something? I'll take a look when i return from vacation next week!
> 
> Possible that I implemented this fix on an outdated version, I will verify!

#3534 fixes some of the issues but still misses edge cases. I will update the tests to cover those edge cases.

**Comment by oddvernes** [comment]
I was trying to reproduce the edge case but think i found another one instead. 

1. Run storybook and go to the disabled option story
2. type am so only the disabled amazon option is in the list
3. press down arrow
Another crash in findindex

**Comment by mhwaage** [comment]
> I was trying to reproduce the edge case but think i found another one instead.
> 
> 1. Run storybook and go to the disabled option story
> 2. type "am" so only the disabled amazon option is in the list
> 3. press down arrow
>    Another crash in findindex

Yeah, this is the same edge case that this PR _should_ be fixing. Is it not fixed by this pr?

**Comment by oddvernes** [comment]
> Yeah, this is the same edge case that this PR _should_ be fixing. Is it not fixed by this pr?

My mistake, the error was in the story 🤦‍♂️ `item.trend === '📉'` should be `item?.trend === '📉'` on line 354

**Review by oddvernes — APPROVED** [review]
LGTM

**Pull request merged**
