### PR TITLE
Change from cricle to circle

### LINKED ISSUE #993: Wrong icon name
`close_cricle_outlined` should be `close_circle_outlined` [here](https://github.com/equinor/design-system/blob/e9c1c64fdf4de744e2dec456b7cab8da06260cb6/libraries/icons/src/data.ts#L882)

### PR DESCRIPTION
**Pull request by maiaht**
Closes #993

### CODE REVIEW

**Review by mimarz — CHANGES_REQUESTED** [review]
Much love ❤️ for providing a fix for this typo 😊

You missed renaming the static svg file for close_circle_outlined [here](https://github.com/equinor/design-system/blob/develop/libraries/static/icons/system-icons/ui-action/close_cricle_outlined.svg) which also needs to be renamed.

**Comment by mimarz** [comment]
Did you fix this using the [assets script](https://github.com/equinor/design-system/blob/develop/apps/figma-broker/Commands.httpie) in figma-broker or just changed files manually? 

All our assets are generated dynamically from Figma, so it will need to be fixed there before we can approve this fix, or else its just going to re-appear next time we run the assets script 🙈

**Comment by maiaht** [comment]
The files were changed manually

**Review by mimarz — APPROVED** [review]
Thanks for your contribution! 👍

**Pull request merged**
