### PR TITLE
Migrate tabs stories to typescript

### PR DESCRIPTION
**Pull request by wenche**
Part of #735

### CODE REVIEW

**Comment by wenche** [comment]
I'm having trouble with the panels example. I tried to add type `number` to the callback function to avoid `any` type. Gives me this
Skjermbilde 2020-11-03 kl  16 08 08
The props are actually like this
Skjermbilde 2020-11-03 kl  16 10 06

So where does the `e: React.FormEvent<HTLMDivElement>` comes from? Is it because of the naming `onChange`? 🤯

**Comment by pomfrida** [comment]
> So where does the `e: React.FormEvent<HTLMDivElement>` comes from? Is it because of the naming `onChange`? 🤯

I have the same problem in #806 
When I was about to change the `children` type after your review this same error came up from nowhere (or Visual Studio was not catching them before for some reason). Use `Omit` to remove `onChange` from `HTMLDivElement` type import. Have no idea why they don't match though.

**Comment by wenche** [comment]
> > So where does the `e: React.FormEvent<HTLMDivElement>` comes from? Is it because of the naming `onChange`? 🤯
> 
> I have the same problem in #806
> When I was about to change the `children` type after your review this same error came up from nowhere (or Visual Studio was not catching them before for some reason). Use `Omit` to remove `onChange` from `HTMLDivElement` type import. Have no idea why they don't match though.

I ❤️  you @pomfrida

**Comment by wenche** [comment]
One last issue with `Tabs`. When I use the controls to play with the component, I'll get a wall of errors in the developer tools console.
Skjermbilde 2020-11-04 kl  08 27 06

I suppose this is because of the mismatch between
```
export type TabsProps = {
  /** The index of the active tab */
  activeTab?: number
  /** The callback function for selecting a tab */
  onChange?: (index: number) => void
  /** Sets the width of the tabs. Tabs can have a maximum width of 360px */
  variant?: Variants
} & Omit<HTMLAttributes<HTMLDivElement>, 'onChange'>
```

and 
```
const Tabs = forwardRef<HTMLDivElement, TabsProps>(function Tabs(
  { activeTab = 0, onChange, onBlur, onFocus, variant = 'minWidth', ...props },
  ref,
)
```
Why is not `onBlur` and `onFocus` in the type? Is this intentionally? @vnys

**Comment by mimarz** [comment]
> One last issue with `Tabs`. When I use the controls to play with the component, I'll get a wall of errors in the developer tools console.
> Skjermbilde 2020-11-04 kl 08 27 06
> 
> I suppose this is because of the mismatch between
> 
> ```
> export type TabsProps = {
>   /** The index of the active tab */
>   activeTab?: number
>   /** The callback function for selecting a tab */
>   onChange?: (index: number) => void
>   /** Sets the width of the tabs. Tabs can have a maximum width of 360px */
>   variant?: Variants
> } & Omit<HTMLAttributes<HTMLDivElement>, 'onChange'>
> ```
> 
> and
> 
> ```
> const Tabs = forwardRef<HTMLDivElement, TabsProps>(function Tabs(
>   { activeTab = 0, onChange, onBlur, onFocus, variant = 'minWidth', ...props },
>   ref,
> )
> ```
> 
> Why is not `onBlur` and `onFocus` in the type? Is this intentionally? @vnys

Because they are defined in `React.HTMLAttributes<HTMLDivElement>`. Why this fails tho 🤷‍♂️

**Comment by pomfrida** [comment]
> > Why is not `onBlur` and `onFocus` in the type? Is this intentionally? @vnys
> 
> Because they are defined in `React.HTMLAttributes<HTMLDivElement>`. Why this fails tho 🤷‍♂️

Could this be the same issue as in #806 where `onChange` expected a function?

**Comment by wenche** [comment]
> Because they are defined in `React.HTMLAttributes<HTMLDivElement>`. Why this fails tho 🤷‍♂️
Hmm, but when we explicit use a function we will normally define it in types even if it is a native prop? Since we use it we should define it? Feels like a mismatch between other components

**Comment by mimarz** [comment]
I had a sneak edit before, but heres the problem @wenche @pomfrida 

We have in some places used to define `onFocus`, `onBlur` and `onChange` properties with default NoOp functions, to avoid defined checking in the code, which is maybe a bit lazy as these are optional props... Suggest we check if its defined before executing in `Tabs`

**Comment by vnys** [comment]
> Why is not `onBlur` and `onFocus` in the type? Is this intentionally? @vnys

I was about to say they were [defined as defaultProps](https://github.com/equinor/design-system/blob/develop/libraries/core-react/src/Tabs/Tabs.jsx#L66-L72) originally, so then I would use default parameters in the function signature or check if they exist as @mimarz suggests.

**Comment by wenche** [comment]
Yes, that would be my suggestion as well. But even optional props used in this way should be declared with ? in types imho?

**Comment by wenche** [comment]
> 
> I was about to say they were [defined as defaultProps](https://github.com/equinor/design-system/blob/develop/libraries/core-react/src/Tabs/Tabs.jsx#L66-L72) originally, so then I would use default parameters in the function signature or check if they exist as @mimarz suggests.

OK, makes sense, so a typescript migration "feature" then

**Review by mimarz — APPROVED** [review]
LGTM 👍

**Pull request merged**
