### PR TITLE
📝 App launcher documentation

### LINKED ISSUE #718: As a developer I need to know how to combine components to implement the App Launcher

### PR DESCRIPTION
**Pull request by martalalik**
Resolves #718

### CODE REVIEW

**Comment by oddvernes** [comment]
I'm wondering if perhaps putting the label below (outside of) the button works better, then the icon is not pushed to the edge (looks weird) and there would be way more space for the label so it is not cut off after 4 letters? Although I see you have done what is in figma where label is inside 48x48 🤔. Maybe there should be input from @equinor/eds-ux 
bilde

**Comment by martalalik** [comment]
I think i follow all the guidelines in [Figam](https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/UI%E2%80%94User-Interface?node-id=18343%3A1628).
And i see your point, maybe the space for the icon & label could be bigger 🤔 ?

**Comment by oddvernes** [comment]
Should show to designers to check if they thought this trough when they made it and if they realize you mostly end up with 3 letters and ellipsis for any words longer than 4 letters

**Comment by benteljones** [comment]
ges.zenhubusercontent.com/617137275a2f3b5f9e07865a/78a86a78-b073-48af-aaca-4ba366123769)

**Comment by benteljones** [comment]
Marta and I have had a review. 😊

**Review by oddvernes — APPROVED** [review]
LGTM

**Pull request merged**
