### PR TITLE
📝 Combobox documentation

### LINKED ISSUE #1912: Document Combobox
Create documentation for Combobox so its easier for our users to understand the intended use for this "new" component when releasing it to public testing.

### PR DESCRIPTION
**Pull request by mimarz**
resolves #1912

### CODE REVIEW

**Comment by oddvernes** [comment]
Should maybe force height on a container so all the examples arent in a tiny window, like the wrapper used in the select stories? 
bilde

**Comment by mimarz** [comment]
> Should maybe force height on a container so all the examples arent in a tiny window, like the wrapper used in the select stories? bilde

yeah, I removed the height as I intended to fix this #1913

**Comment by oddvernes** [comment]
But the outer div owned by storybook have overflow hidden on it
bilde

**Comment by mimarz** [comment]
> But the outer div owned by storybook have overflow hidden on it bilde

Was thinking we could use portals the same way we do for `Menu` & `Popover`? 🤔

**Review by oddvernes — APPROVED** [review]
Other than compact not being set with variable, LGTM 👍

**Pull request merged**
