### PR TITLE
Typescript for button story

### PR DESCRIPTION
**Pull request by wenche**
Part of #735

### CODE REVIEW

**Comment by wenche** [comment]
I don't think the `as` prop is easy to understand, and we should indeed do something about how we do this.
Skjermbilde 2020-10-26 kl  14 56 15

**Comment by wenche** [comment]
I'm struggling a bit with the `type` prop as well, it should have a default to 'button'? But the code is a bit strange here 😓 
Skjermbilde 2020-10-26 kl  16 19 53

**Comment by wenche** [comment]
I solved the default type props by using @default in the comment 🤷‍♀️  But the code feels a bit fuzzy here.

**Review by mimarz — APPROVED** [review]
LGTM 👍

**Comment by vnys** [comment]
> I solved the default type props by using @default in the comment 🤷‍♀️ But the code feels a bit fuzzy here.

Didn’t it work with `someProp = 'default value'`?

**Comment by wenche** [comment]
> > I solved the default type props by using @default in the comment 🤷‍♀️ But the code feels a bit fuzzy here.
> 
> Didn’t it work with `someProp = 'default value'`?

Not the way it was solved, ref. "fuzzy code" 👍

**Pull request merged**
