### PR TITLE
Table: Hover & Error state on rows

### LINKED ISSUE #940: Add missing table states
States for active and error cell in table. 
How to show active and hover on both row and cell?

Edit:
~- [ ] Active state, row only~ Replaced by #981
- [x] Hover state, row only
- [x] Error (Validation) state, cell only

### PR DESCRIPTION
**Pull request by mimarz**
resolves #940

### CODE REVIEW

**Review by wenche — CHANGES_REQUESTED** [review]
I think we should remove the Tooltip until we have a better example? Perhaps an i-icon or something just to indicate that there's _something_ to explore

**Comment by mimarz** [comment]
> I think we should remove the Tooltip until we have a better example? Perhaps an i-icon or something just to indicate that there's _something_ to explore

Replaced with an warning icon in first col as this display example is also viable if you have many many columns

**Comment by wenche** [comment]
> > I think we should remove the Tooltip until we have a better example? Perhaps an i-icon or something just to indicate that there's _something_ to explore
> 
> Replaced with an warning icon in first col as this display example is also viable if you have many many columns

Sry, but I still don't understand this example 😬  And empty thead cell? 🤔

**Comment by mimarz** [comment]
> > > I think we should remove the Tooltip until we have a better example? Perhaps an i-icon or something just to indicate that there's _something_ to explore
> > 
> > 
> > Replaced with an warning icon in first col as this display example is also viable if you have many many columns
> 
> Sry, but I still don't understand this example 😬 And empty thead cell? 🤔

Should have been an icon in thead cell maybe, but removed it alltogether, saving it for later when we have more features that work together for a better example then :)

**Review by wenche — APPROVED** [review]
LGTM 👍

**Pull request merged**
