### PR TITLE
a11y issues with Storefront

### LINKED ISSUE #900: Fix multiple content issues
Vi have several issues with duplicated content, caused by e.g dead links, duplicate titles and so on.

Skjermbilde 2020-11-20 kl  10 58 14

### LINKED ISSUE #901: Avoid dead links in Component status table
The automated generation of the Component status table from the yaml file is not sophisticated enough for components that does not have a separate page in components folder.

See Icon and Typography at the bottom, and Select that does not yet exist.

Find a more flexible approach to avoid links that redirects to the frontpage.

### PR DESCRIPTION
**Pull request by wenche**
resolve #900  and #894

### CODE REVIEW

**Review by pomfrida — APPROVED** [review]
LGTM 👍

**Review by mimarz — APPROVED** [review]
LGTM 👍

**Pull request merged**
