### PR TITLE
Update Menu hover state

### LINKED ISSUE #1363: Update hover state for the menu in dev
According to issue #1048 the hover state of the text in the menu has now be changed to bold

### PR DESCRIPTION
**Pull request by pomfrida**
Resolves #1363

### CODE REVIEW

**Comment by pomfrida** [comment]
So this update ended up a bit more complex than expected. We have auto width menus so the width gets auto adjusted when text becomes bold on hover. I added a hack to avoid the auto width adjustment but this only works for simple menus (when there's only one child and the child is a string). 

Example of menu working as expected:
https://user-images.githubusercontent.com/31915755/120807460-41f7ad00-c548-11eb-9a96-fc0e9215701c.mov

Example of complex menu not working ideal (as there's more than one child and combination of different types):
https://user-images.githubusercontent.com/31915755/120807595-6a7fa700-c548-11eb-8d6d-5554a4bea310.mov

**Comment by pomfrida** [comment]
Blocked by #1426

**Comment by pomfrida** [comment]
Changes done as suggested in #1426 and ready for review now

**Review by mimarz — APPROVED** [review]
LGTM 👍

**Pull request merged**
