### PR TITLE
👷 Move storybook, use Github actions and AZ Storage

### LINKED ISSUE #1010: Setup github actions for storybook releases
- [x] Move Storybook to core-react folder
- [x] Remove superfluous files
- [x] Deploy Storybook to Azure Storage Blob
- [x] Make sure storybook files don't leak into npm package

### PR DESCRIPTION
**Pull request by vnys**
- Installed fresh storybook under core-react
- Moved stories from apps/storybook-react
- Added placeholder for screens (app examples)

To make screen examples, uncomment the relevant line in .storybook/main.js

Tested build and deploy from my own branch, currently running at https://edsstoragestorybookdev.z16.web.core.windows.net/

~I just used the standard introduction page, so there are a couple of more things to move over, but the Github action works as expected, and so does building core-react – no story types in the build.~

There are a lot of files in this pr, as you would expect when moving all the stories. No need to spend time on the stories, they are unchanged for the most part except how we import core-react into the stories, which is now using a webpack alias, e.g. `import { Avatar, AvatarProps, Typography } from '@components'`

I have resisted the tempation to make changes to the stories as much as possible, as that’s outside the scope of this pr – but we need to do some spring cleaning.

resolves #1010

### CODE REVIEW

**Comment by vnys** [comment]
Note to self: Remove svg icons in stories/assets

**Comment by vnys** [comment]
…also added an action to deploy #1046 to https://edsstoragedev.z16.web.core.windows.net/

**Review by mimarz — CHANGES_REQUESTED** [review]
* There seems to be a lot of new svgs under `/storybook/assets` that are not used. Part of the default storybook installation?

* We plan on hosting this from `edsstoragedev` no?

**Comment by vnys** [comment]
> * There seems to be a lot of new svgs under `/storybook/assets` that are not used. Part of the default storybook installation?

That’s correct. I left them there because I thought we could use them ourselves in the documentation stories, but it’s probably better to use our own icons.

**Comment by vnys** [comment]
> * We plan on hosting this from `edsstoragedev` no?

No. We need a dev and prod environment. You can only have one static site for each account, so the cleanest way to do that is to have one storage account for each environment.

**Comment by mimarz** [comment]
> > * We plan on hosting this from `edsstoragedev` no?
> 
> No. We need a dev and prod environment. You can only have one static site for each account, so the cleanest way to do that is to have one storage account for each environment.

Yeah, maybe we should also clean up some of the web-services we have running that aren't used also 🙈

**Review by mimarz — APPROVED** [review]
LGTM 🇵🇱

**Comment by vnys** [comment]
> Yeah, maybe we should also clean up some of the web-services we have running that aren't used also 🙈

Yes, we’ll have to go through that after the transition. Don’t think there are a lot of costs involved, but some spring cleaning is much needed.

**Pull request merged**
